include: package:flutter_lints/flutter.yaml

analyzer:
  # Do NOT treat warnings as errors
  errors:
    unused_element: error
    unused_field: error
    unused_local_variable: error
    unused_import: error
    dead_code: error
    missing_required_param: error
    missing_return: error
    todo: ignore

  exclude:
    - "**/*.g.dart"
    - "**/generated/**"
    - "build/**"
    - ".dart_tool/**"